
###Task get api
GET http://localhost:8000/api/v1/task


###Task post api
POST http://localhost:8000/api/v1/task
Content-Type: application/json

//make sure to have a space between header 

{
    "task":"watching Tv",
    "hr":1222
}


###Task delete api
DELETE  http://localhost:8000/api/v1/task

